### ISSUE TITLE
Format casing for Go types 

### ISSUE THREAD

**Issue by sanderblue** [newrelic/tutone#57]
### Objective

Format casing in Go-style properly for acronyms and initialisms:

| GraphQL format | Go format      |
| -------------- | -------------- |
| `AccountId`    | `AccountID`    |
| `AccountIds`   | `AccountIDs`   |
| `ApiAccessKey` | `APIAccessKey` |
| `UserId`       | `UserID`       |

### Acceptance Criteria
- All generated Go types have proper casing and pass some level of linting

**Comment by jthurman42** [comment]
This exists for Go, though there is an issue to refactor the code from schema to the golang package
